ci: fix incorrect ref and linting issues

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,12 +19,19 @@ jobs:
             echo "Not on the main branch. Skipping the curl command."
             exit 0
           fi
+        shell: bash
 
       - name: Curl Render to run new deploy
         if: success()
         run: |
-          CURL_URL="https://api.render.com/deploy/${{secrets.RENDER_DEPLOY_APP_TOKEN}}?key=${{secrets.RENDER_DEPLOY_KEY}}&ref=${{ github.event.release.target_commitish }}"
+          COMMIT_SHA=$(git rev-parse HEAD)
+          CURL_URL="https://api.render.com/deploy/${{secrets.RENDER_DEPLOY_APP_TOKEN}}?key=${{secrets.RENDER_DEPLOY_KEY}}&ref=${COMMIT_SHA}"
 
           HTTP_STATUS=$(curl -i -X POST "${CURL_URL}" -o /dev/null -w "%{http_code}")
           
-          if [[ $HTTP_STATUS -ge 200 && $HTTP_STATUS -lt 
+          if [[ $HTTP_STATUS -ge 200 && $HTTP_STATUS -lt 300 ]]; then
+            echo "Render build started successfully."
+          else
+            echo "Render build failed with a status code of ${HTTP_STATUS}"
+            exit 1
+          fi
